# Generated by Django 4.2.5 on 2023-10-03 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appreciation',
            options={'verbose_name': 'Appreciation', 'verbose_name_plural': 'Appreciations'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categories', 'verbose_name_plural': 'Categories'},
        ),
    ]
